name: Makefile CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/locale/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        always-auth: false
        node-version: 14
        architecture: x64
        cache: npm
        cache-dependency-path: package-lock.json
       
    - name: Install
      run: npm ci
      
    - name: Clean
      run: make clean
      
    - name: Generate
      run: make generate
      
    - name: GitHub Push
      # You may pin to the exact commit or the version.
      # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: 'first_project'
        # Destination branch to push changes
        branch: 'main' # optional, default is master
