name: Makefile CI

on:
  push:
    paths:
      - 'app/locale/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2   

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        always-auth: false
        node-version: 14
        architecture: x64
        cache: npm
        cache-dependency-path: package-lock.json
       
    - name: Install
      run: npm install
      
    - name: Clean
      run: make clean
      
    - name: Extract
      run: make extract
      
    - name: Generate
      run: make generate
