name: Locale CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
      with:
        always-auth: false
        node-version: 16
        architecture: x64
        cache: npm
        cache-dependency-path: package-lock.json

    - uses: lyricwulf/abc@v1
      with:
        linux: gettext

    - name: Install
      run: npm install

    - name: Translate
      run: npm run translate

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.12.0
