name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clean
      run: make clean
      
    - name: Extract
      run: make extract
      
    - name: Generate
      run: make generate
